SilverStripe\Admin\ModelAdmin:
  extensions:
    - VersionedModelAdminUpdateFormExtension
SilverStripe\Assets\Image:
  extensions:
    - Azt3k\SS\Extensions\AbcImageExtension
SilverStripe\Assets\File:
  extensions:
    - Azt3k\SS\Extensions\AbcFileExtension
SilverStripe\Admin\LeftAndMain:
  extensions:
    - Azt3k\SS\Extensions\AbcLeftAndMainExtension
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Azt3k\SS\Extensions\AbcSiteTreeExtension
SilverStripe\Security\Security:
  extensions:
    - Azt3k\SS\Extensions\AbcSecurityExtension
SilverStripe\Control\Controller:
  extensions:
    - Azt3k\SS\Extensions\AbcControllerExtension
# HTMLText:
#   extensions:
#     - HTMLTextExtension
